//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public string Address { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> PayTypeID { get; set; }
        public Nullable<decimal> PayRate { get; set; }
        public Nullable<decimal> MaxAmountExpense { get; set; }
    
        public virtual PayType PayType { get; set; }
        public virtual Position Position { get; set; }
    }
}
